# Realistic GAF-listed roofing contractors within 25 miles of ZIP 10013 (Tribeca, Manhattan).
# In production this data would be scraped from:
#   https://www.gaf.com/en-us/roofing-contractors/residential?distance=25
# using a headless browser (Playwright/Puppeteer) since the site is JS-rendered.

SEED_CONTRACTORS = [
    {
        "name": "Empire Roofing & Waterproofing",
        "address": "234 Atlantic Ave",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11201",
        "phone": "(718) 555-0142",
        "website": "https://empireroofingny.com",
        "gaf_tier": "master_elite",
        "distance_miles": 2.8,
        "review_count": 187,
        "avg_rating": 4.9,
        "years_in_business": 22,
    },
    {
        "name": "Tri-State Roof Pros",
        "address": "88 Newark Ave",
        "city": "Jersey City",
        "state": "NJ",
        "zip_code": "07302",
        "phone": "(201) 555-0317",
        "website": "https://tristateroofpros.com",
        "gaf_tier": "master_elite",
        "distance_miles": 4.1,
        "review_count": 143,
        "avg_rating": 4.8,
        "years_in_business": 15,
    },
    {
        "name": "Apex Roofing Solutions",
        "address": "55 Hackensack Ave",
        "city": "Kearny",
        "state": "NJ",
        "zip_code": "07032",
        "phone": "(201) 555-0489",
        "website": "https://apexroofingsolutions.net",
        "gaf_tier": "master_elite",
        "distance_miles": 9.3,
        "review_count": 211,
        "avg_rating": 4.7,
        "years_in_business": 19,
    },
    {
        "name": "BK Roof & Repair Co",
        "address": "1022 Flatbush Ave",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11226",
        "phone": "(718) 555-0208",
        "website": "https://bkroofrepair.com",
        "gaf_tier": "certified_plus",
        "distance_miles": 6.2,
        "review_count": 94,
        "avg_rating": 4.7,
        "years_in_business": 11,
    },
    {
        "name": "Premier Roofing NYC",
        "address": "415 E 149th St",
        "city": "Bronx",
        "state": "NY",
        "zip_code": "10455",
        "phone": "(718) 555-0371",
        "website": "https://premierroofingnyc.com",
        "gaf_tier": "certified_plus",
        "distance_miles": 8.4,
        "review_count": 76,
        "avg_rating": 4.6,
        "years_in_business": 8,
    },
    {
        "name": "Garden State Roofing",
        "address": "290 Market St",
        "city": "Newark",
        "state": "NJ",
        "zip_code": "07102",
        "phone": "(973) 555-0153",
        "website": "https://gardenstateroofing.net",
        "gaf_tier": "certified_plus",
        "distance_miles": 13.7,
        "review_count": 58,
        "avg_rating": 4.5,
        "years_in_business": 14,
    },
    {
        "name": "Five Boroughs Roofing",
        "address": "78-12 Jamaica Ave",
        "city": "Queens",
        "state": "NY",
        "zip_code": "11421",
        "phone": "(718) 555-0629",
        "website": "",
        "gaf_tier": "certified",
        "distance_miles": 10.8,
        "review_count": 112,
        "avg_rating": 4.4,
        "years_in_business": 17,
    },
    {
        "name": "Hudson Roofing & Construction",
        "address": "44 Palisade Ave",
        "city": "Yonkers",
        "state": "NY",
        "zip_code": "10701",
        "phone": "(914) 555-0244",
        "website": "https://hudsonroofingco.com",
        "gaf_tier": "certified",
        "distance_miles": 16.5,
        "review_count": 47,
        "avg_rating": 4.8,
        "years_in_business": 9,
    },
    {
        "name": "Island Shield Roofing",
        "address": "1840 Victory Blvd",
        "city": "Staten Island",
        "state": "NY",
        "zip_code": "10314",
        "phone": "(718) 555-0492",
        "website": "https://islandshieldroofing.com",
        "gaf_tier": "certified",
        "distance_miles": 12.3,
        "review_count": 38,
        "avg_rating": 4.3,
        "years_in_business": 6,
    },
    {
        "name": "Metro Roof Systems",
        "address": "320 Communipaw Ave",
        "city": "Jersey City",
        "state": "NJ",
        "zip_code": "07304",
        "phone": "(201) 555-0581",
        "website": "",
        "gaf_tier": "certified",
        "distance_miles": 5.6,
        "review_count": 29,
        "avg_rating": 4.2,
        "years_in_business": 4,
    },
    {
        "name": "Boroughs Roofing & Repair",
        "address": "25-11 Jackson Ave",
        "city": "Long Island City",
        "state": "NY",
        "zip_code": "11101",
        "phone": "(718) 555-0963",
        "website": "https://boroughsroofing.com",
        "gaf_tier": "none",
        "distance_miles": 3.9,
        "review_count": 41,
        "avg_rating": 4.6,
        "years_in_business": 7,
    },
    {
        "name": "Skyline Contractors Inc",
        "address": "142-65 Roosevelt Ave",
        "city": "Flushing",
        "state": "NY",
        "zip_code": "11354",
        "phone": "(718) 555-0736",
        "website": "https://skylinecontractorsinc.com",
        "gaf_tier": "none",
        "distance_miles": 14.1,
        "review_count": 23,
        "avg_rating": 4.5,
        "years_in_business": 3,
    },
    {
        "name": "Atlantic Roofing Group",
        "address": "560 Bay St",
        "city": "Staten Island",
        "state": "NY",
        "zip_code": "10304",
        "phone": "(718) 555-0817",
        "website": "",
        "gaf_tier": "none",
        "distance_miles": 11.2,
        "review_count": 15,
        "avg_rating": 4.1,
        "years_in_business": 2,
    },
    {
        "name": "Urban Shield Roofing",
        "address": "98 Ferry St",
        "city": "Newark",
        "state": "NJ",
        "zip_code": "07105",
        "phone": "(973) 555-0294",
        "website": "https://urbanshieldroofing.com",
        "gaf_tier": "none",
        "distance_miles": 15.8,
        "review_count": 8,
        "avg_rating": 3.9,
        "years_in_business": 1,
    },
    {
        "name": "Pinnacle Roof Solutions",
        "address": "88 Linden Ave",
        "city": "East Orange",
        "state": "NJ",
        "zip_code": "07017",
        "phone": "(973) 555-0412",
        "website": "https://pinnacleroofsolutions.net",
        "gaf_tier": "none",
        "distance_miles": 18.3,
        "review_count": 6,
        "avg_rating": 4.0,
        "years_in_business": 2,
    },
]
